### ISSUE TITLE
Question about the performance gain

### ISSUE THREAD

**Issue by shuangshuangguo** [MalongTech/CurriculumNet#4]
Hi, I have a confusion about the performance gain.
I guess model D in your paper runs more iterations than model B, so I can say model D has seen more samples than Model B. 
If so, can I say that's the reason for performance gain?

**Comment by mscottml** [comment]
Thanks for your question, @shuangshuangguo . All models A, B, C, D were trained with a same number of iterations – 70,000, which is shown in Fig. 4, and indicated in Section 3.4 in our paper https://arxiv.org/pdf/1808.01097.pdf

Regarding performance gain. Model B is trained by only using the clean subset, while model D is trained by using the full CurriculumNet learning strategy with a 3-subset curriculum: clean, noisy and highly noisy subsets. Model D’s performance advantage for weakly labeled datasets is not due to seeing more iterations than Model B, but because it adopts the learning strategy where it learns with increasing difficulty; that is, training is proceeded sequentially from easier tasks to harder ones.

Model D is trained using a multi-stage learning process that learns a standard neural network more efficiently with the enhanced capability for handling massive noisy labels. This allows the model to learn basic but clear visual information from each category, serving as the fundamental features. Additionally, when the model trained in the first stage converges, we continue the learning process by adding the noisy data, where images have more significant visual diversity, allowing the model to learn more meaningful and discriminative features from harder samples. Although the noisy data may include incorrect labels, it roughly preserves the main structure of the data, and thus leads to performance improvement. Finally, the model is further trained by adding the highly noisy data which contains a large number of visually irrelevant images with incorrect labels. The deep features learned by following the first two-stage curriculum are able to capture the main underlying structure of the data. We observe that the highly noisy data added in the last stage does not impact negatively to the learned data structure. By contrast, it improves the generalization capability of the model, and allows the model to avoid over-fitting over the clean data, by providing a manner of regularization. A final model D is obtained when the training converges in the last stage, where the three subsets are all combined.
